import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { CalendarDays, ChevronRight, History, KeyRound, LogOut, Menu, Scissors, UserRound, X } from 'lucide-react';
import { Link, NavLink, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api } from '../lib/api';
import { currency, phoneDigits, phoneMask } from '../lib/format';
import type { Appointment, User } from '../types';

const statusLabel = { PENDING: 'Pendente', CONFIRMED: 'Confirmado', COMPLETED: 'Concluído', CANCELLED: 'Cancelado', NO_SHOW: 'Não compareceu' };
interface CancelResponse { appointment: { id: string; status: Appointment['status']; cancelledAt: string }; whatsAppUrl: string | null }

export function AccountPage() {
  const { user, updateUser, logout } = useAuth(); const location = useLocation(); const navigate = useNavigate();
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState(''); const [menu, setMenu] = useState(false);
  const [profile, setProfile] = useState({ name: user?.name || '', phone: user?.phone || '', birthDate: user?.birthDate?.slice(0, 10) || '' });
  const page = location.pathname.includes('/perfil') ? 'profile' : location.pathname.includes('/seguranca') ? 'security' : 'appointments';
  useEffect(() => { api<Appointment[]>('/appointments/me').then(setAppointments).catch((e: Error) => setMessage(e.message)).finally(() => setLoading(false)); }, []);
  const cancel = async (id: string) => { if (!window.confirm('Deseja cancelar este agendamento? O WhatsApp será aberto para avisar o barbeiro.')) return; try { const response = await api<CancelResponse>(`/appointments/${id}/cancel`, { method: 'PATCH' }); setAppointments((items) => items.map((item) => item.id === id ? { ...item, status: 'CANCELLED' } : item)); setMessage(response.whatsAppUrl ? 'Agendamento cancelado. Abrindo o WhatsApp para avisar o barbeiro...' : 'Agendamento cancelado. O profissional verá a alteração no painel.'); if (response.whatsAppUrl) window.setTimeout(() => window.location.assign(response.whatsAppUrl!), 700); } catch (e) { setMessage(e instanceof Error ? e.message : 'Não foi possível cancelar.'); } };
  const saveProfile = async (e: FormEvent) => { e.preventDefault(); setMessage(''); try { const updated = await api<User>('/account/profile', { method: 'PATCH', body: JSON.stringify({ ...profile, phone: phoneDigits(profile.phone), birthDate: profile.birthDate || null }) }); setProfile({ name: updated.name, phone: updated.phone || '', birthDate: updated.birthDate?.slice(0, 10) || '' }); updateUser(updated); setMessage('Perfil atualizado com sucesso.'); } catch (err) { setMessage(err instanceof Error ? err.message : 'Não foi possível atualizar.'); } };
  const changePassword = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); setMessage(''); try { await api('/account/password', { method: 'PATCH', body: JSON.stringify({ currentPassword: data.get('currentPassword'), newPassword: data.get('newPassword') }) }); await logout(); void navigate('/entrar', { replace: true }); } catch (err) { setMessage(err instanceof Error ? err.message : 'Não foi possível alterar a senha.'); } };
  const signOut = async () => { await logout(); void navigate('/'); };
  const now = new Date(); const upcoming = appointments.filter((item) => new Date(item.startAt) > now && ['PENDING', 'CONFIRMED'].includes(item.status)); const history = appointments.filter((item) => !upcoming.includes(item));
  return <main className="dashboard account-dashboard"><aside className={menu ? 'dashboard-sidebar open' : 'dashboard-sidebar'}><button className="sidebar-close" onClick={() => setMenu(false)}><X /></button><Link to="/" className="dashboard-logo"><img src="/assets/los-pit/logo/logo-los-pit.png" alt="Los Pit" /></Link><div className="dashboard-user"><div>{user?.name.charAt(0)}</div><span><strong>{user?.name}</strong><small>{user?.email}</small></span></div><nav><NavLink to="/conta/agendamentos"><CalendarDays /> Agendamentos</NavLink><NavLink to="/conta/perfil"><UserRound /> Meu perfil</NavLink><NavLink to="/conta/seguranca"><KeyRound /> Segurança</NavLink></nav><button className="sidebar-logout" onClick={() => { void signOut(); }}><LogOut /> Sair da conta</button></aside>
    <section className="dashboard-main account-main"><header className="account-page-header"><button className="sidebar-toggle" onClick={() => setMenu(true)}><Menu /></button><div><small>Área do cliente</small><h1>{page === 'appointments' ? 'Meus agendamentos' : page === 'profile' ? 'Meu perfil' : 'Segurança'}</h1></div>{page === 'appointments' && <Link to="/agendar" className="button button-small">Novo agendamento</Link>}</header><div className="dashboard-content account-content"><div className="form-message" aria-live="polite">{message}</div>
      {page === 'appointments' && <>{loading ? <div className="loading-line" /> : <><AppointmentSection title="Próximos horários" icon={<CalendarDays />} items={upcoming} onCancel={cancel} /><AppointmentSection title="Histórico" icon={<History />} items={history} /></>}</>}
      {page === 'profile' && <form className="settings-form" onSubmit={(e) => { void saveProfile(e); }}><h2>Dados pessoais</h2><p>Mantenha seus dados atualizados para facilitar o atendimento.</p><label>Nome completo<input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} /></label><label>E-mail<input disabled value={user?.email || ''} /></label><label>WhatsApp<input value={phoneMask(profile.phone)} onChange={(e) => setProfile({ ...profile, phone: phoneDigits(e.target.value) })} /></label><label>Data de nascimento<input type="date" value={profile.birthDate} onChange={(e) => setProfile({ ...profile, birthDate: e.target.value })} /></label><button className="button">Salvar alterações</button></form>}
      {page === 'security' && <form className="settings-form" onSubmit={(e) => { void changePassword(e); }}><h2>Alterar senha</h2><p>A alteração encerra as outras sessões ativas.</p><label>Senha atual<input required name="currentPassword" type="password" /></label><label>Nova senha<input required minLength={8} name="newPassword" type="password" /></label><button className="button">Alterar senha</button></form>}
    </div></section>
  </main>;
}

function AppointmentSection({ title, icon, items, onCancel }: { title: string; icon: ReactNode; items: Appointment[]; onCancel?: (id: string) => void }) { return <section className="appointment-section"><h2>{icon}{title}<span>{items.length}</span></h2>{items.length === 0 ? <div className="dashboard-empty"><Scissors /><p>Você ainda não possui agendamentos.</p><Link to="/agendar" className="text-link">Agendar agora →</Link></div> : <div className="appointment-list">{items.map((item) => <article key={item.id}><time><strong>{new Intl.DateTimeFormat('pt-BR', { day: '2-digit' }).format(new Date(item.startAt))}</strong><span>{new Intl.DateTimeFormat('pt-BR', { month: 'short' }).format(new Date(item.startAt)).replace('.', '')}</span></time><div className="appointment-info"><span className={`status ${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span><h3>{item.services.map((service) => service.nameSnapshot).join(' + ')}</h3><p>{item.professional.name} · {new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit', timeZone: 'America/Fortaleza' }).format(new Date(item.startAt))}</p></div><strong>{currency(item.totalCents)}</strong>{onCancel && <button className="cancel-link" onClick={() => onCancel(item.id)}>Cancelar</button>}<ChevronRight /></article>)}</div>}</section>; }
