import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { CalendarDays, CheckCircle2, Images, LayoutDashboard, LogOut, Menu, Scissors, Settings, UserRound, UsersRound, X } from 'lucide-react';
import { Link, NavLink, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api } from '../lib/api';
import { currency, duration } from '../lib/format';
import type { Appointment, Professional, Service, Settings as BusinessSettings } from '../types';

interface GalleryItem { id: string; url: string; alt: string; category?: string | null; active: boolean }
const nav = [
  ['/admin', LayoutDashboard, 'Visão geral'], ['/admin/agenda', CalendarDays, 'Agenda'], ['/admin/agendamentos', CheckCircle2, 'Agendamentos'],
  ['/admin/profissionais', UsersRound, 'Profissionais'], ['/admin/servicos', Scissors, 'Serviços'], ['/admin/clientes', UserRound, 'Clientes'],
  ['/admin/galeria', Images, 'Galeria'], ['/admin/configuracoes', Settings, 'Configurações']
] as const;

export function AdminPage() {
  const { user, logout } = useAuth(); const location = useLocation(); const navigate = useNavigate();
  const [menu, setMenu] = useState(false); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [services, setServices] = useState<Service[]>([]);
  const [professionals, setProfessionals] = useState<Professional[]>([]); const [gallery, setGallery] = useState<GalleryItem[]>([]);
  const [settings, setSettings] = useState<BusinessSettings>({ name: 'Los Pit Barber Shop', timezone: 'America/Fortaleza' });
  const page = location.pathname.split('/')[2] || 'dashboard';
  const load = useCallback(async () => {
    setLoading(true); setMessage('');
    try {
      const [a, s, p, g, cfg] = await Promise.all([
        api<Appointment[]>('/admin/appointments'), api<Service[]>('/admin/services'), api<Professional[]>('/admin/professionals'),
        api<GalleryItem[]>('/admin/gallery'), api<BusinessSettings>('/settings')
      ]); setAppointments(a); setServices(s); setProfessionals(p); setGallery(g); setSettings(cfg);
    } catch (e) { setMessage(e instanceof Error ? e.message : 'Não foi possível carregar o painel.'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const updateStatus = async (id: string, status: Appointment['status']) => { try { await api(`/admin/appointments/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); setAppointments((items) => items.map((item) => item.id === id ? { ...item, status } : item)); } catch (e) { setMessage(e instanceof Error ? e.message : 'Erro ao atualizar.'); } };
  const signOut = async () => { await logout(); void navigate('/'); };
  return <main className="dashboard admin-dashboard"><aside className={menu ? 'dashboard-sidebar open' : 'dashboard-sidebar'}><button className="sidebar-close" onClick={() => setMenu(false)}><X /></button><Link to="/" className="dashboard-logo"><img src="/assets/los-pit/logo/logo-los-pit.png" alt="Los Pit" /></Link><div className="admin-badge">Administração</div><nav>{nav.map(([to, Icon, label]) => <NavLink key={to} end={to === '/admin'} to={to} onClick={() => setMenu(false)}><Icon />{label}</NavLink>)}</nav><button className="sidebar-logout" onClick={() => { void signOut(); }}><LogOut /> Sair do painel</button></aside>
    <section className="dashboard-main"><header><button className="sidebar-toggle" onClick={() => setMenu(true)}><Menu /></button><div><small>Painel administrativo</small><h1>{nav.find(([to]) => (to === '/admin' ? location.pathname === to : location.pathname.startsWith(to)))?.[2] || 'Administração'}</h1></div><div className="admin-user"><span>{user?.name}</span><div>{user?.name.charAt(0)}</div></div></header><div className="dashboard-content"><div className="form-message">{message}</div>{loading ? <div className="loading-line" /> : <>
      {page === 'dashboard' && <AdminOverview appointments={appointments} professionals={professionals} services={services} />}
      {(page === 'agenda' || page === 'agendamentos') && <AppointmentsAdmin appointments={appointments} onStatus={updateStatus} />}
      {page === 'servicos' && <ServicesAdmin services={services} reload={load} />}
      {page === 'profissionais' && <ProfessionalsAdmin professionals={professionals} services={services} reload={load} />}
      {page === 'galeria' && <GalleryAdmin gallery={gallery} reload={load} />}
      {page === 'configuracoes' && <SettingsAdmin settings={settings} setSettings={setSettings} />}
      {page === 'clientes' && <div className="admin-empty"><UserRound /><h2>Clientes cadastrados</h2><p>Os dados pessoais ficam disponíveis nos detalhes de agendamentos e pela API administrativa protegida.</p></div>}
    </>}</div></section>
  </main>;
}

function AdminOverview({ appointments, professionals, services }: { appointments: Appointment[]; professionals: Professional[]; services: Service[] }) {
  const today = new Date().toDateString(); const todayItems = appointments.filter((item) => new Date(item.startAt).toDateString() === today);
  return <><div className="admin-kpis"><div><CalendarDays /><small>Hoje</small><strong>{todayItems.length}</strong><span>agendamentos</span></div><div><UsersRound /><small>Equipe ativa</small><strong>{professionals.filter((p) => p.active).length}</strong><span>profissionais</span></div><div><Scissors /><small>Catálogo</small><strong>{services.filter((s) => s.active).length}</strong><span>serviços ativos</span></div></div><AppointmentsAdmin appointments={todayItems} onStatus={() => undefined} compact /></>;
}

function AppointmentsAdmin({ appointments, onStatus, compact = false }: { appointments: Appointment[]; onStatus: (id: string, status: Appointment['status']) => void; compact?: boolean }) {
  return <section className="admin-panel"><div className="admin-panel-title"><div><h2>{compact ? 'Agenda de hoje' : 'Todos os agendamentos'}</h2><p>{appointments.length} registros encontrados</p></div></div>{appointments.length === 0 ? <div className="admin-empty"><CalendarDays /><p>Nenhum agendamento para exibir.</p></div> : <div className="admin-table"><table><thead><tr><th>Data</th><th>Cliente</th><th>Serviço</th><th>Profissional</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>{appointments.map((item) => <tr key={item.id}><td><strong>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short' }).format(new Date(item.startAt))}</strong><small>{new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(new Date(item.startAt))}</small></td><td><strong>{item.customerName}</strong><small>{item.customerPhone}</small></td><td>{item.services.map((s) => s.nameSnapshot).join(', ')}</td><td>{item.professional.name}</td><td>{currency(item.totalCents)}</td><td><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span></td><td><select value={item.status} onChange={(e) => onStatus(item.id, e.target.value as Appointment['status'])}><option value="CONFIRMED">Confirmado</option><option value="COMPLETED">Concluído</option><option value="CANCELLED">Cancelado</option><option value="NO_SHOW">Não compareceu</option></select></td></tr>)}</tbody></table></div>}</section>;
}

function ServicesAdmin({ services, reload }: { services: Service[]; reload: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const create = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); await api('/admin/services', { method: 'POST', body: JSON.stringify({ name: data.get('name'), slug: String(data.get('name')).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-'), description: data.get('description'), durationMin: Number(data.get('durationMin')), priceCents: Math.round(Number(data.get('price')) * 100), active: true, featured: false }) }); setOpen(false); await reload(); };
  const toggle = async (service: Service) => { await api(`/admin/services/${service.id}`, { method: 'PATCH', body: JSON.stringify({ active: !service.active }) }); await reload(); };
  return <section className="admin-panel"><div className="admin-panel-title"><div><h2>Catálogo de serviços</h2><p>Preços são armazenados em centavos.</p></div><button className="button button-small" onClick={() => setOpen(true)}>Novo serviço</button></div><div className="admin-item-list">{services.map((service) => <article key={service.id}><Scissors /><div><h3>{service.name}</h3><p>{service.description}</p><small>{duration(service.durationMin)}</small></div><strong>{currency(service.priceCents)}</strong><button className={service.active ? 'state-on' : 'state-off'} onClick={() => { void toggle(service); }}>{service.active ? 'Ativo' : 'Inativo'}</button></article>)}</div>{open && <Modal title="Novo serviço" close={() => setOpen(false)}><form className="admin-form" onSubmit={(e) => { void create(e); }}><label>Nome<input name="name" required /></label><label>Descrição<textarea name="description" required /></label><label>Duração (min)<input name="durationMin" type="number" min="5" required /></label><label>Preço (R$)<input name="price" type="number" min="0" step="0.01" required /></label><button className="button">Cadastrar serviço</button></form></Modal>}</section>;
}

function ProfessionalsAdmin({ professionals, services, reload }: { professionals: Professional[]; services: Service[]; reload: () => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const create = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const name = String(data.get('name')); const whatsappNumber = String(data.get('whatsappNumber') || '').replace(/\D/g, ''); await api('/admin/professionals', { method: 'POST', body: JSON.stringify({ name, slug: name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-'), specialty: data.get('specialty'), bio: data.get('bio'), photoUrl: data.get('photoUrl') || undefined, whatsappNumber: whatsappNumber || undefined, serviceIds: data.getAll('services') }) }); setOpen(false); await reload(); };
  const saveWhatsapp = async (professional: Professional, value: string) => { const whatsappNumber = value.replace(/\D/g, ''); if (whatsappNumber === (professional.whatsappNumber || '')) return; await api(`/admin/professionals/${professional.id}`, { method: 'PATCH', body: JSON.stringify({ whatsappNumber: whatsappNumber || null }) }); await reload(); };
  return <section className="admin-panel"><div className="admin-panel-title"><div><h2>Equipe</h2><p>Cadastre o WhatsApp de cada profissional com DDI e DDD.</p></div><button className="button button-small" onClick={() => setOpen(true)}>Novo profissional</button></div>{professionals.length === 0 ? <div className="admin-empty"><UsersRound /><p>Nenhum profissional cadastrado.</p></div> : <div className="admin-item-list">{professionals.map((item) => <article key={item.id}>{item.photoUrl ? <img src={item.photoUrl} alt="" /> : <UserRound />}<div><h3>{item.name}</h3><p>{item.specialty}</p></div><label className="professional-whatsapp">WhatsApp<input defaultValue={item.whatsappNumber || ''} placeholder="5585999999999" inputMode="numeric" onBlur={(event) => { void saveWhatsapp(item, event.target.value); }} /></label><span className={item.active ? 'state-on' : 'state-off'}>{item.active ? 'Ativo' : 'Inativo'}</span></article>)}</div>}{open && <Modal title="Novo profissional" close={() => setOpen(false)}><form className="admin-form" onSubmit={(e) => { void create(e); }}><label>Nome real<input name="name" required /></label><label>Especialidade<input name="specialty" /></label><label>WhatsApp com DDI e DDD<input name="whatsappNumber" inputMode="numeric" placeholder="5585999999999" pattern="\d{12,13}" /></label><label>Biografia<textarea name="bio" /></label><label>URL da foto<input name="photoUrl" /></label><fieldset><legend>Serviços realizados</legend>{services.filter((s) => s.active).map((s) => <label className="check-label" key={s.id}><input type="checkbox" name="services" value={s.id} /><span>{s.name}</span></label>)}</fieldset><button className="button">Cadastrar profissional</button></form></Modal>}</section>;
}

function GalleryAdmin({ gallery, reload }: { gallery: GalleryItem[]; reload: () => Promise<void> }) { const [open, setOpen] = useState(false); const create = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); await api('/admin/gallery', { method: 'POST', body: JSON.stringify({ url: data.get('url'), alt: data.get('alt'), category: data.get('category'), active: true, sortOrder: gallery.length }) }); setOpen(false); await reload(); }; return <section className="admin-panel"><div className="admin-panel-title"><div><h2>Galeria</h2><p>Imagens oficiais e seus textos alternativos.</p></div><button className="button button-small" onClick={() => setOpen(true)}>Adicionar imagem</button></div><div className="admin-gallery">{gallery.map((item) => <figure key={item.id}><img src={item.url} alt={item.alt} /><figcaption>{item.alt}</figcaption></figure>)}</div>{open && <Modal title="Adicionar imagem" close={() => setOpen(false)}><form className="admin-form" onSubmit={(e) => { void create(e); }}><label>URL do asset<input name="url" required placeholder="/assets/los-pit/gallery/..." /></label><label>Texto alternativo<input name="alt" required /></label><label>Categoria<input name="category" /></label><button className="button">Adicionar</button></form></Modal>}</section>; }

function SettingsAdmin({ settings, setSettings }: { settings: BusinessSettings; setSettings: (value: BusinessSettings) => void }) { const [message, setMessage] = useState(''); const save = async (e: FormEvent) => { e.preventDefault(); try { const updated = await api<BusinessSettings>('/admin/settings', { method: 'PATCH', body: JSON.stringify(settings) }); setSettings(updated); setMessage('Configurações salvas.'); } catch (err) { setMessage(err instanceof Error ? err.message : 'Erro ao salvar.'); } }; return <form className="settings-form admin-panel" onSubmit={(e) => { void save(e); }}><h2>Informações oficiais</h2><p>Campos vazios não aparecem publicamente.</p><label>Nome<input value={settings.name} onChange={(e) => setSettings({ ...settings, name: e.target.value })} /></label><label>Endereço<input value={settings.address || ''} onChange={(e) => setSettings({ ...settings, address: e.target.value })} /></label><label>WhatsApp<input value={settings.phone || ''} onChange={(e) => setSettings({ ...settings, phone: e.target.value })} /></label><label>E-mail<input type="email" value={settings.email || ''} onChange={(e) => setSettings({ ...settings, email: e.target.value })} /></label><label>Instagram (URL)<input value={settings.instagram || ''} onChange={(e) => setSettings({ ...settings, instagram: e.target.value })} /></label><label>Fuso horário<input value={settings.timezone} onChange={(e) => setSettings({ ...settings, timezone: e.target.value })} /></label><div className="form-message">{message}</div><button className="button">Salvar configurações</button></form>; }

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="admin-modal" role="dialog" aria-modal="true" onMouseDown={(e) => { if (e.currentTarget === e.target) close(); }}><div><header><h2>{title}</h2><button onClick={close}><X /></button></header>{children}</div></div>; }
